// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HospitalManagementSystemApi.Data;
using HospitalManagementSystemApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace HospitalManagementSystemApi.Data.Configurations
{
    public partial class AppointmentConfiguration : IEntityTypeConfiguration<Appointment>
    {
        public void Configure(EntityTypeBuilder<Appointment> entity)
        {
            entity.HasKey(e => e.appointment_id)
                .HasName("PK__Appointm__A50828FCC37145B2");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Appointment> entity);
    }
}
