// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HospitalManagementSystemApi.Data;
using HospitalManagementSystemApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace HospitalManagementSystemApi.Data.Configurations
{
    public partial class DoctorConfiguration : IEntityTypeConfiguration<Doctor>
    {
        public void Configure(EntityTypeBuilder<Doctor> entity)
        {
            entity.HasKey(e => e.doctor_id)
                .HasName("PK__Doctor__F39935642BCBA917");

            entity.Property(e => e.doc_address).IsUnicode(false);

            entity.Property(e => e.doc_first_name).IsUnicode(false);

            entity.Property(e => e.doc_last_name).IsUnicode(false);

            entity.Property(e => e.doc_ph_no).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Doctor> entity);
    }
}
