// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HospitalManagementSystemApi.Data;
using HospitalManagementSystemApi.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;


namespace HospitalManagementSystemApi.Data.Configurations
{
    public partial class PatientConfiguration : IEntityTypeConfiguration<Patient>
    {
        public void Configure(EntityTypeBuilder<Patient> entity)
        {
            entity.HasKey(e => e.patient_id)
                .HasName("PK__Patient__4D5CE4768FAF7C31");

            entity.Property(e => e.pat_address).IsUnicode(false);

            entity.Property(e => e.pat_first_name).IsUnicode(false);

            entity.Property(e => e.pat_insurance_no).IsUnicode(false);

            entity.Property(e => e.pat_last_name).IsUnicode(false);

            entity.Property(e => e.pat_ph_no).IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Patient> entity);
    }
}
