// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HospitalManagementSystemApi.Models
{
    public partial class Doctor
    {
        [Key]
        public int doctor_id { get; set; }
        [Required]
        [StringLength(15)]
        public string doc_first_name { get; set; }
        [Required]
        [StringLength(15)]
        public string doc_last_name { get; set; }
        [Required]
        [StringLength(15)]
        public string doc_ph_no { get; set; }
        [Required]
        [StringLength(40)]
        public string doc_address { get; set; }
    }
}