// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace HospitalManagementSystemApi.Models
{
    public partial class Patient
    {
        [Key]
        public int patient_id { get; set; }
        [Required]
        [StringLength(15)]
        public string pat_first_name { get; set; }
        [Required]
        [StringLength(15)]
        public string pat_last_name { get; set; }
        [Required]
        [StringLength(10)]
        public string pat_insurance_no { get; set; }
        [Required]
        [StringLength(15)]
        public string pat_ph_no { get; set; }
        [Required]
        [StringLength(40)]
        public string pat_address { get; set; }
    }
}